# THIS IS A DEVELOPER CONFIGURATION FILE
# IT IS NOT AN EXAMPLE OF SOMETHING YOU DEPLOY
# I ONLY USE IT FOR DEVELOPING HEADPLANE

networks:
  headplane-dev:
    name: "headplane-dev"
    driver: "bridge"
services:
  headscale:
    image: "headscale/headscale:0.25.1"
    container_name: "headscale"
    restart: "unless-stopped"
    command: "serve"
    networks:
      - "headplane-dev"
    volumes:
      - "./.cache/headscale:/var/lib/headscale"
      - "./test:/etc/headscale"
    ports:
      - "8080:8080"
    environment:
      TZ: "America/New_York"
