apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: headplane-integrated
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: headplane-integrated
subjects:
- kind: ServiceAccount
  name: headplane-integrated