{{- if not .Values.server.cookieSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headplane.fullname" . }}-cookie
  labels:
    {{- include "headplane.labels" . | nindent 4 }}
stringData:
  {{ .Values.server.cookieSecret.secretKey | default "cookie-secret" }}: {{ include "headplane.cookieSecret" . }}
{{- end }}
{{- if .Values.oidc.enabled }}
{{- if not .Values.oidc.clientSecret.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headplane.fullname" . }}-oidc
  labels:
    {{- include "headplane.labels" . | nindent 4 }}
stringData:
  {{ .Values.oidc.clientSecret.secretKey | default "client-secret" }}: {{ required "oidc.clientSecret.value is required when not using existingSecret" .Values.oidc.clientSecret.value }}
{{- end }}
{{- end }}
