---
apiVersion: v1
kind: Secret
metadata:
  name: headplane-config
type: Opaque
stringData:
  config.yaml: |
    server:
{{- toYaml .Values.headplane.config.server | nindent 6 }}
      cookie_secret: {{ include "headplane.cookieSecret" . | quote }}
    headscale:
{{- toYaml .Values.headplane.config.headscale | nindent 6 }}
    integration:
{{- toYaml .Values.headplane.config.integration | nindent 6 }}
{{- if .Values.headplane.oidc.enabled }}
    oidc:
      issuer: {{ .Values.headplane.oidc.issuer | quote }}
      disable_api_key_login: {{ .Values.headplane.oidc.disable_api_key_login | quote }}
      token_endpoint_auth_method: {{ .Values.headplane.oidc.token_endpoint_auth_method | quote }}
      redirect_uri: {{ .Values.headplane.oidc.redirect_uri | quote }}
      client_id: {{ .Values.headplane.oidc.client_id | quote }}
      headscale_api_key: {{ .Values.headplane.oidc.headscale_api_key | default "placeholder-token-will-be-replaced-by-job" | quote }}
{{- end }}
