---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headplane
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-relay
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headscale-token
  namespace: {{ .Release.Namespace }}
