{{ if not .Values.headplane.config.cookieSecret.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: headplane-cookie-secret
stringData:
  cookie-secret: {{ include "headplane.cookieSecret" . }}
{{- end }}
{{- if and .Values.headplane.config.oidc.enabled }}
{{- if not .Values.headplane.config.oidc.clientSecret.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: headplane-oidc-client-secret
stringData:
  client-secret: {{ required "headplane plaintext client secret value required" .Values.headplane.config.oidc.clientSecret.value }}
{{- end }}
{{- if (and (not .Values.headplane.config.oidc.headscaleApiKey.secretName) (not .Values.headplane.config.generateCredentials)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: headscale-api-key
stringData:
  api-key: {{ required "headplane plaintext headscale api key required" .Values.headplane.config.oidc.headscaleApiKey.value }}
{{- end }}
{{- end }}