apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale
data:
  config.yaml: |
    server_url: {{ .Values.headscale.config.url }}
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 127.0.0.1:9090
    grpc_listen_addr: 127.0.0.1:50443
    grpc_allow_insecure: false
    noise:
      private_key_path: /var/lib/headscale/noise_private.key
    prefixes:
      v4: 100.64.0.0/10
      v6: fd7a:115c:a1e0::/48
      allocation: sequential
    derp:
      server:
        enabled: false
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      paths: []
      auto_update_enabled: true
      update_frequency: 24h
    disable_check_updates: true
    ephemeral_node_inactivity_timeout: 30m
    database:
      type: sqlite
      gorm:
        prepare_stmt: true
        parameterized_queries: true
        skip_err_record_not_found: true
        slow_threshold: 1000
      sqlite:
        path: /var/lib/headscale/db.sqlite
        write_ahead_log: true
        wal_autocheckpoint: 1000
    log:
      format: text
      level: info
    policy:
      mode: database
    dns:
      magic_dns: {{ .Values.headscale.config.dns.magicDns }}
      base_domain: {{ .Values.headscale.config.dns.baseDomain }}
      {{- if .Values.headscale.config.dns.nameservers }}
      nameservers:
        {{- if .Values.headscale.config.dns.nameservers.global }}
        global: {{- toYaml .Values.headscale.config.dns.nameservers.global | nindent 10 }}
        {{- end }}
        {{- if .Values.headscale.config.dns.nameservers.split }}
        split: {{- toYaml .Values.headscale.config.dns.nameservers.split | nindent 10 }}
        {{- end }}
      {{- end }}
    unix_socket: /var/lib/headscale/headscale.sock
    unix_socket_permission: "0770"
    {{- if .Values.headscale.config.oidc.enabled }}
    oidc:
      only_start_if_oidc_is_available: {{ .Values.headscale.config.oidc.startupCheck }}
      issuer: {{ .Values.headscale.config.oidc.issuerUrl }}
      client_id: {{ .Values.headscale.config.oidc.clientId }}
      client_secret_path: /var/secrets/headscale/oidc/client-secret
      expiry: 180d
      use_expiry_from_token: false
      pkce:
        enabled: {{ .Values.headscale.config.oidc.pkceEnabled }}
        method: S256
    {{- end }}
    logtail:
      enabled: false
    randomize_client_port: false
